### HEALTH SECTOR ###

HEALTH_THEMES = {
    "HOSPITAL",
    "WB_HEALTH_SYSTEMS",
    "SOC_GENERALHEALTH",
    "HEALTH_INSTITUTION",
    "MEDICAL",
    "HEALTH_PANDEMIC",
    "TAX_FNCACT_NURSE",
    "TAX_FNCACT_DOCTOR",
    "TAX_FNCACT_PHYSICIAN",
    "HEALTHCARE",
}

CYBER_THEMES = {
    "CYBER_ATTACK",
    "TAX_FNCACT_HACKER",
    "RANSOMWARE",
    "DATA_BREACH",
    "EPU_SECURITY_CYB",
    "CYBERSECURITY",
    "TAX_FNCACT_CYBERCRIMINAL",
    "WB_IMFWEO_DIGITAL",
}

DRUG_SHORTAGE_THEMES = {
    "SHORTAGE",
    "PHARMACEUTICAL_SUPPLY_CHAIN",
    "ESSENTIAL_MEDICINES",
    "MANUFACTURING_OF_DRUGS",
    "PHARMACEUTICALS",
    "GENERIC_DRUGS",
    "PHARMACEUTICAL_PRICING",
    "PHARMACEUTICAL_POLICY",
    "PHARMACEUTICAL_REGULATION",
    "QUALITY_ASSURANCE_FOR_PHARMACEUTICALS",
    "FINANCING_OF_DRUGS",
    "RATIONAL_SELECTION_AND_USE_OF_DRUGS",
}

DEVICE_SHORTAGE_THEMES = {
    "MEDICAL_EQUIPMENT",
    "HEALTH_TECHNOLOGIES",
    "PROCUREMENT_OF_HEALTH_TECHNOLOGIES",
    "MEDICAL_SUPPLIES_FINANCE",
}

NATURAL_DISASTER_THEMES = {"NATURAL_DISASTER"}

HEALTH_SUBSECTOR_THEMES = {
    "drug_shortage": DRUG_SHORTAGE_THEMES,
    "medical_device_shortage": DEVICE_SHORTAGE_THEMES,
    "cyber_attack": CYBER_THEMES,
    "natural_disaster": NATURAL_DISASTER_THEMES,
}

### TEST SECTOR ###

TEST_SECTOR_THEMES = {
    "TEST_THEME_1",
    "TEST_THEME_2",
    "TEST_THEME_3",
}

TEST_SUBSECTOR_1_THEMES = {
    "TEST_SUBSECTOR_1_THEME_1",
    "TEST_SUBSECTOR_1_THEME_2",
    "TEST_SUBSECTOR_1_THEME_3",
}

TEST_SUBSECTOR_2_THEMES = {
    "TEST_SUBSECTOR_2_THEME_1",
    "TEST_SUBSECTOR_2_THEME_2",
    "TEST_SUBSECTOR_2_THEME_3",
}

TEST_SUBSECTOR_THEMES = {
    "subsector_1": TEST_SUBSECTOR_1_THEMES,
    "subsector_2": TEST_SUBSECTOR_2_THEMES,
}

SECTOR_THEMES = {
    "health": (HEALTH_THEMES, HEALTH_SUBSECTOR_THEMES),
    "test": (TEST_SECTOR_THEMES, TEST_SUBSECTOR_THEMES),
}
