### HEALTH SECTOR ###

HEALTH_THEMES = {
    "HOSPITAL",
    "WB_HEALTH_SYSTEMS",
    "SOC_GENERALHEALTH",
    "HEALTH_INSTITUTION",
    "MEDICAL",
    "HEALTH_PANDEMIC",
    "TAX_FNCACT_NURSE",
    "TAX_FNCACT_DOCTOR",
    "TAX_FNCACT_PHYSICIAN",
    "HEALTHCARE",
}

CYBER_THEMES = {
    "CYBER_ATTACK",
    "TAX_FNCACT_HACKER",
    "RANSOMWARE",
    "DATA_BREACH",
    "EPU_SECURITY_CYB",
    "CYBERSECURITY",
    "TAX_FNCACT_CYBERCRIMINAL",
    "WB_IMFWEO_DIGITAL",
}

DRUG_SHORTAGE_THEMES = {
    "SHORTAGE",
    "PHARMACEUTICAL_SUPPLY_CHAIN",
    "ESSENTIAL_MEDICINES",
    "MANUFACTURING_OF_DRUGS",
    "PHARMACEUTICALS",
    "GENERIC_DRUGS",
    "PHARMACEUTICAL_PRICING",
    "PHARMACEUTICAL_POLICY",
    "PHARMACEUTICAL_REGULATION",
    "QUALITY_ASSURANCE_FOR_PHARMACEUTICALS",
    "FINANCING_OF_DRUGS",
    "RATIONAL_SELECTION_AND_USE_OF_DRUGS",
}

DEVICE_SHORTAGE_THEMES = {
    "MEDICAL_EQUIPMENT",
    "HEALTH_TECHNOLOGIES",
    "PROCUREMENT_OF_HEALTH_TECHNOLOGIES",
    "MEDICAL_SUPPLIES_FINANCE",
}

NATURAL_DISASTER_THEMES = {"NATURAL_DISASTER"}

HEALTH_SUBSECTOR_THEMES = {
    "drug_shortage": DRUG_SHORTAGE_THEMES,
    "medical_device_shortage": DEVICE_SHORTAGE_THEMES,
    "cyber_attack": CYBER_THEMES,
    "natural_disaster": NATURAL_DISASTER_THEMES,
}

### CRITICAL MANUFACTURING SECTOR ###

CRITICAL_MANUFACTURING_THEMES = {
    "WB_1281_MANUFACTURING",
    "EMERG_INDUSTRIALACCIDENT",
    "MANMADE_DISASTER_INDUSTRIAL",
    "TAX_FNCACT_INDUSTRIAL",
    "WB_281_ICT_INDUSTRY_AND_SERVICES",
}

PRIMARY_METALS_MANUFACTURING_THEMES = {
    "WB_1699_METAL_ORE_MINING",
    "ENV_METALS",
    "TAX_FNCACT_METALLURGIST",
    "TAX_FNCACT_METALWORKER",
    "WB_2931_IRON",
    "TAX_FNCACT_IRONWORKER",
    "TAX_FNCACT_IRONMONGER",
    "TAX_FNCACT_STEELWORKER",
    "WB_895_MINING_SYSTEMS",
    "WB_2934_COPPER",
    "WB_2935_NICKEL",
    "WB_2933_ZINC",
    "TAX_FNCACT_FOUNDRYMAN",
    "TAX_FNCACT_SMELTER",
    "TAX_FNCACT_FORGER",
}

MACHINERY_MANUFACTURING_THEMES = {
    "TAX_FNCACT_HYDRAULICS_ENGINEER",
}

ELECTRICAL_EQUIPMENT_MANUFACTURING_THEMES = {
    "TAX_FNCACT_ELECTRICAL_ENGINEER",
}

TRANSPORTATION_EQUIPMENT_MANUFACTURING_THEMES = {
    "WB_1812_TRANSPORT_EQUIPMENT",
    "TAX_FNCACT_SHIPWRIGHT",
    "TAX_FNCACT_SHIPFITTER",
    "TAX_FNCACT_AEROSPACE_ENGINEER",
    "TAX_FNCACT_RAILROAD",
    "WB_166_RAILWAYS",
    "WB_1227_AUTOMOTIVE_VALUE_CHAIN",
}

CRITICAL_MANUFACTURING_SUBSECTOR_THEMES = {
    "primary_metals_manufacturing": PRIMARY_METALS_MANUFACTURING_THEMES,
    "machinery_manufacturing": MACHINERY_MANUFACTURING_THEMES,
    "electrical_equipment_manufacturing": ELECTRICAL_EQUIPMENT_MANUFACTURING_THEMES,
    "transportation_equipment_manufacturing": TRANSPORTATION_EQUIPMENT_MANUFACTURING_THEMES,
}

### TEST THEMES ###

TEST_SECTOR_THEMES = {
    "TEST_THEME_1",
    "TEST_THEME_2",
    "TEST_THEME_3",
}

TEST_SUBSECTOR_1_THEMES = {
    "TEST_SUBSECTOR_1_THEME_1",
    "TEST_SUBSECTOR_1_THEME_2",
    "TEST_SUBSECTOR_1_THEME_3",
}

TEST_SUBSECTOR_2_THEMES = {
    "TEST_SUBSECTOR_2_THEME_1",
    "TEST_SUBSECTOR_2_THEME_2",
    "TEST_SUBSECTOR_2_THEME_3",
}

TEST_SUBSECTOR_THEMES = {
    "subsector_1": TEST_SUBSECTOR_1_THEMES,
    "subsector_2": TEST_SUBSECTOR_2_THEMES,
}

### THEME NAMES ###

SECTOR_THEMES = {
    "health": (HEALTH_THEMES, HEALTH_SUBSECTOR_THEMES),
    "critical_manufacturing": (
        CRITICAL_MANUFACTURING_THEMES,
        CRITICAL_MANUFACTURING_SUBSECTOR_THEMES,
    ),
    "test": (
        TEST_SECTOR_THEMES,
        TEST_SUBSECTOR_THEMES,
    ),
}
